---
title: "Untitled"
author: "Prof. Mauricio"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

library(tidyverse)
library(Deriv)
library(directlabels)
```

## R Markdown

```{r, fig.retina=2, fig.height=2, fig.width=3}

cobb <- function(L){
  -0.5*L^3+6*L^2-L
  }


L <- seq(from= 0.1, to=10, by=0.1)
Q <- funcao_prod(L)

data <- data.frame(L,Q=round(Q,2))


data %>% 
  ggplot(aes(L,Q))+
  geom_line(size=1.2)+
  scale_y_continuous(limits=c(0,150))+
  scale_x_continuous(limits = c(0, 8))+
  theme_classic()+
  labs(y="Unidades de Produto",
       x="Trabalhadores")



PMg <- Deriv(cobb, "L")

data %>% 
  mutate(PMg = PMg(L),
         PMe = Q/L) %>% 
  select(-Q) %>% 
  pivot_longer(2:3) %>% 
  ggplot(aes(L,value, color=name))+
  geom_line(size=1.2)+
  scale_y_continuous(limits=c(0,30))+
  scale_x_continuous(limits = c(0, 8))+
  theme_classic()+
  geom_dl(aes(label = name), method = "smart.grid")+
  theme(legend.position = "none")+
  labs(y="Unidades de Produto",
       x="Trabalhadores")
```

```{r}

library(gt)
data2 <- data.frame(L=1:10)

data2 <- data2 %>% 
  mutate(Q=cobb(L),
         PMg = PMg(L),
         PMe = Q/L) 

data2 %>% 
  gt::gt()

```

```{r}
data %>% 
  mutate(PMg = PMg(L),
         PMe = Q/L,
         RMgP = PMg*10) %>% 
  select(L,RMgP) %>% 
  ggplot(aes(L,RMgP))+
  geom_line()+
  scale_y_continuous(limits = c(0, 250))+
  scale_x_continuous(limits = c(0,8))+
  theme_classic()
```

